In [9]:
import pandas as pd
import re
import numpy as np

In [2]:
df = pd.read_csv("extracted_quotes.csv", index_col = None)

In [3]:
df.head(5)

quote  \
0  Un homme heureux est trop content du présent p...   
1  Autoritätsdusel ist der größte Feind der Wahrh...   
2  Lieber Habicht! / Es herrscht ein weihevolles ...   
3                                              E=mc²   
4  The mass of a body is a measure of its energy ...   

                                              source           author  \
0  A happy man is too satisfied with the present ...  Albert Einstein   
1  Blind obedience to authority is the greatest e...  Albert Einstein   
2  Dear Habicht, / Such a solemn air of silence h...  Albert Einstein   
3  The equation originally expressed the equivale...  Albert Einstein   
4  Ist die Trägheit eines Körpers von seinem Ener...  Albert Einstein   

  heading_context  
0           1890s  
1           1900s  
2           1900s  
3           1900s  
4           1900s

Let's perform some exploratory dataset analysis on the dataset

In [4]:
df.shape

(30000, 4)

In [15]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   quote            29984 non-null  object
 1   source           22914 non-null  object
 2   author           30000 non-null  object
 3   heading_context  20671 non-null  object
dtypes: object(4)
memory usage: 937.6+ KB
None


In [17]:
# Missing values
print(df.isna().sum())

quote                16
source             7086
author                0
heading_context    9329
dtype: int64


There are some quotes which are null lets see those.

In [18]:
null_quotes = df[df['quote'].isna() | df['quote'].str.strip().eq('')]

print(f"Number of null/empty quotes: {len(null_quotes)}")
display(null_quotes[['quote', 'author', 'source', 'heading_context']].head(20))

Number of null/empty quotes: 16


quote            author  \
13703   NaN  Chinese proverbs   
13704   NaN  Chinese proverbs   
13708   NaN  Chinese proverbs   
13709   NaN  Chinese proverbs   
13712   NaN  Chinese proverbs   
13713   NaN  Chinese proverbs   
13714   NaN  Chinese proverbs   
13715   NaN  Chinese proverbs   
13717   NaN  Chinese proverbs   
13718   NaN  Chinese proverbs   
13720   NaN  Chinese proverbs   
13721   NaN  Chinese proverbs   
13724   NaN  Chinese proverbs   
13728   NaN  Chinese proverbs   
13731   NaN  Chinese proverbs   
13732   NaN  Chinese proverbs   

                                                  source heading_context  
13703  Transliteration (pinyin): Chángjiāng hòulàng t...              Ch  
13704  Transliteration (pinyin): Dú wàn juǎn shū bùrú...               D  
13708  Transliteration (pinyin): Fù zhài zǐ huán. Tra...               F  
13709  Transliteration (pinyin): Hài rén zhī xīn bù k...               H  
13712  Transliteration (pinyin): Kōngxuéláifēng, wèib...               K  
13713  Transliteration (pinyin): Liángyào kǔkǒu Tradi...               L  
13714  Transliteration: Yǒu qí fù bì yǒu qí zǐ. Havin...               L  
13715  Transliteration (pinyin): Rén suàn bùrú tiān s...               R  
13717  Transliteration (pinyin): Sān gè héshàng méi s...               S  
13718  Transliteration (pinyin): Sǐ mǎ dāng huó mǎ yī...               S  
13720  Transliteration (pinyin): Shòu rén yǐ yú bùrú ...              Sh  
13721  Transliteration (pinyin): Shù dǎo húsūn sàn. T...              Sh  
13724  Transliteration (pinyin): Tiān gāo huángdì yuǎ...               T  
13728  Transliteration (pinyin): Yǒu qián néng shǐ gu...               Y  
13731  Transliteration (pinyin): Zìzhù zhě tiānzhù. T...               Z  
13732  Transliteration (pinyin): Zǎoqǐ de niǎo er yǒu...               Z

The probelm is that the chinese proverbs are in chinese language and while extracting the quotes we only focused on the english language characters that's why they are null.

Let's see if all the chinese proverbs are like this

In [27]:
chinese_quotes = df[df['author'].str.strip().eq('Chinese proverbs')]

print(f"Number of chinese quotes: {len(chinese_quotes)}")
display(chinese_quotes[['quote', 'author', 'source', 'heading_context']].head(20))

Number of chinese quotes: 61


quote            author  \
13699                                          ， ， ， ； 。  Chinese proverbs   
13700                                          小洞不补，大洞吃苦  Chinese proverbs   
13701                                        读书须用意，一字值千金  Chinese proverbs   
13702                                    宝剑锋从磨砺出，梅花香自苦寒来  Chinese proverbs   
13703                                                NaN  Chinese proverbs   
13704                                                NaN  Chinese proverbs   
13705  ， ， https: //learnchinesewithabdul. com/chines...  Chinese proverbs   
13706  https: //archive. org/details/diversproverbsw0...  Chinese proverbs   
13707                                                  ,  Chinese proverbs   
13708                                                NaN  Chinese proverbs   
13709                                                NaN  Chinese proverbs   
13710                                                  ，  Chinese proverbs   
13711                             Jiŭ fā xīn fù zhī yán.  Chinese proverbs   
13712                                                NaN  Chinese proverbs   
13713                                                NaN  Chinese proverbs   
13714                                                NaN  Chinese proverbs   
13715                                                NaN  Chinese proverbs   
13716                                                  一  Chinese proverbs   
13717                                                NaN  Chinese proverbs   
13718                                                NaN  Chinese proverbs   

                                                  source heading_context  
13699  Transliteration (pinyin): Bù wén bù ruò wén zh...               B  
13700  Transliteration: xiǎo dòng bù bǔ, dà dòng chī ...               B  
13701  Transliteration: dú shū xū yòng yì, yī zì zhí ...               B  
13702  Transliteration: Bǎojiàn fēng cóng mólì chū, m...               B  
13703  Transliteration (pinyin): Chángjiāng hòulàng t...              Ch  
13704  Transliteration (pinyin): Dú wàn juǎn shū bùrú...               D  
13705  pinyin: fēng xiàng biàn shí, yǒu rén jìng qián...               F  
13706  Transliteration (pinyin): Fáng rén zhī xīn bùk...               F  
13707  Transliteration (pinyin): Fú wú chóng zhì, huò...               F  
13708  Transliteration (pinyin): Fù zhài zǐ huán. Tra...               F  
13709  Transliteration (pinyin): Hài rén zhī xīn bù k...               H  
13710  Transliteration (pinyin): Jīnrì shì, jīnrì bì....               J  
13711  Wine makes words from secrets. Meaning: Alcoho...               J  
13712  Transliteration (pinyin): Kōngxuéláifēng, wèib...               K  
13713  Transliteration (pinyin): Liángyào kǔkǒu Tradi...               L  
13714  Transliteration: Yǒu qí fù bì yǒu qí zǐ. Havin...               L  
13715  Transliteration (pinyin): Rén suàn bùrú tiān s...               R  
13716  Transliteration (pinyin): Ròu bāozi dǎ gǒu 一 q...               R  
13717  Transliteration (pinyin): Sān gè héshàng méi s...               S  
13718  Transliteration (pinyin): Sǐ mǎ dāng huó mǎ yī...               S

In [7]:
pd.set_option('display.max_colwidth', None)
print(df.loc[13716, ['quote', 'source']])

quote                                                                                                                                                                                                                                      一
source    Transliteration (pinyin): Ròu bāozi dǎ gǒu 一 qù bù huítóu. Traditional: 肉包子打狗一去不回頭 Simplified: 肉包子打狗一去不回头 To hit a dog with a meat-bun, so it leaves never turning around. Meaning: Punishment gives less incentive than a reward.
Name: 13716, dtype: object


In [41]:
# pd.set_option('display.max_colwidth', None)

df.loc[df['author'] == "Chinese proverbs", 'source']

13699                                                                                                                                                        Transliteration (pinyin): Bù wén bù ruò wén zhī, wén zhī bù ruò jiàn zhī, jiàn zhī bù ruò zhīzhī, zhīzhī bù ruò xíng zhī; xué zhìyú xíng zhī ér zhǐ yǐ. Traditional: 不聞不若聞之，聞之不若見之，見之不若知之，知之不若行之；學至於行之而止矣 Simplified: 不闻不若闻之，闻之不若见之，见之不若知之，知之不若行之；学至于行之而止矣 From Xun Zi (荀子 8. 儒效 23）.
13700    Transliteration: xiǎo dòng bù bǔ, dà dòng chī kǔ A small hole not mended in time will become a big hole much more difficult to mend. English equivalent: "What's past is prologue. " or "A stitch in time saves nine. " Meaning: Fix something while it can be fixed. Don't wait until it's too late to do so. "Destroy the seed of evil, or it will grow up to your ruin. " Aesop, "The Swallow and the Other Birds" (c. 6th century BC)
13701                                                                                     Transliteration: dú shū xū yòng yì, yī z

WHen the source has the chinese alphabet and link attached to it in the source the extractor has avoided it as html link. So it is not able to extract it. But when the source is in english it has successfully extracted it.

Okay, now I understand. Multiple quotes on the chinese proverb page are written as a link and those proverbs have not been extracted and the translation has been mistakenly extracted in the source. 

So we have two options
* to drop the columns for which the quote is NaN value.
* to switch the source and the quote value where the quote is NaN. Because the source contains the translation and in a way it is also a quote.
    we will decide in the preprocessing part

Let's see the quotes which don't have both author and source.

In [14]:
missing_author_source = df[
    (df['author'].isna() | df['author'].str.strip().eq('')) &
    (df['source'].isna() | df['source'].str.strip().eq(''))
]

print(f"Quotes without both author and source: {len(missing_author_source)}")

Quotes without both author and source: 0


There aren't any quotes which don't have both source and author, which is a good thing. Let's check for the null values of each column.

Let's see how many unique authors do we have

In [29]:
unique_authors = df['author'].nunique(dropna=True)

# List of unique authors (optional)
authors_list = df['author'].dropna().unique()

print(f"Number of unique authors: {unique_authors}")
print(authors_list[:20])  # show first 20 authors

Number of unique authors: 368
['Albert Einstein' 'Disputed with Albert Einstein'
 'Misattributed to Albert Einstein' 'unknown' 'Zen proverbs'
 'Wikiquote: Templates' 'Latin proverbs' 'Nero' 'Martin Luther King Jr.'
 'Disputed with Martin Luther King Jr.'
 'Misattributed to Martin Luther King Jr.' 'John Cage' 'Harry S. Truman'
 'Disputed with Harry S. Truman' 'Misattributed to Harry S. Truman'
 'Bertrand Russell' 'Disputed with Bertrand Russell'
 'Misattributed to Bertrand Russell' 'Oscar Wilde'
 'Disputed with Oscar Wilde']


We have 368 unique authors but there is one mistake while extracting these from dump. Albert einstien and misattributed to ALbert Einstien and disputed with albert Einstin are three different authors in the author list. Which is a entity fragmentation.

Let's see who are the authors with most quotes and the authors with the least quotes.

In [30]:
author_counts = df['author'].value_counts().reset_index()
author_counts.columns = ['author', 'quote_count']

# Sort descending (most quotes first)
most_quotes = author_counts.sort_values(by='quote_count', ascending=False)

# Sort ascending (least quotes first)
least_quotes = author_counts.sort_values(by='quote_count', ascending=True)

print("Authors with most quotes:")
print(most_quotes.head(10))  # top 10

print("\nAuthors with least quotes:")
print(least_quotes.head(10))  # bottom 10

Authors with most quotes:
                   author  quote_count
0                 unknown         5342
1              Last words         1051
2        English proverbs          897
3          George W. Bush          674
4       Winston Churchill          504
5     Ralph Waldo Emerson          486
6        Bertrand Russell          480
7  Martin Luther King Jr.          460
8         John F. Kennedy          454
9          Thomas Carlyle          412

Authors with least quotes:
                                       author  quote_count
367          Disputed with Edsger W. Dijkstra            1
337       Misattributed to Edsger W. Dijkstra            1
336             Misattributed to Helen Keller            1
335         Misattributed to William Congreve            1
334             Misattributed to Walt Whitman            1
333             Disputed with Harry S. Truman            1
332            Misattributed to Stephen Crane            1
331               Disputed with H. L. Mencken

The misattributed and disputed we can deal later but the Last words and English Proverbs we should have a look.

Let's see if the source of the English Proverbs and Last Words are meaningful. Because the author does not contain any meaningfull information

In [31]:
# For English proverbs
print("\nEnglish proverbs:")
print(df[df['author'] == "English proverbs"].head(20))



English proverbs:
                                                   quote  \
23386               Absence makes the heart grow fonder.   
23387                       Long absent, soon forgotten.   
23388         The absent are always in the wrong. (1640)   
23389  Accidents will happen in the best families. (1...   
23390                   Actions speak louder than words.   
23391  Admiration: our polite recognition of another ...   
23392            He who does not advance goes backwards.   
23393                Advice most needed is least heeded.   
23394          Advise none to marry or go to war. (1640)   
23395                             Advisers run no risks.   
23396        All is fair in love and war. (17th century)   
23397         All is well that ends well. (14th century)   
23398    America is God's melting-pot. (Israel Zangwill)   
23399  Good riding at two anchors, men have told, for...   
23400  Anger makes dull men witty, but it keeps them ...   
23401  Do not let sun

I can see that the Quotes are scrapped very beautifully but the sources are missing for some I don't know why. I have used the same code to scrape all but for some the source are missing but for some it is present.

Should I revisit the extraction code? For now I think I should not because we dont have any quote for which both author and source are missing. SO collectively they will provide some information about the quote. SO for now I am not going to chaneg the extraction code code

In [32]:
# For English proverbs
print("\nLast Words:")
print(df[df['author'] == "Last words"].head(20))



Last Words:
                                                   quote  \
14083                                        No comment.   
14084                                I did what I could.   
14085                                         Van Halen!   
14086  Come Lord Jesus, come quickly, finish in me th...   
14087  يام السرور التي صفت لي دون تكدير في مدة سلطاني...   
14088  من در حال رفتن هستم و شما مي خواهيد غذا بخورم؟...   
14089                         I don't know. [Attributed]   
14090  שלף חרבך ומותתני פן-יאמרו לי, אשה הרגתהו (Shel...   
14091  May the Most High God preserve thee from destr...   
14092                It's okay! Gun's not loaded. . see?   
14093  Ja, maar niet te veel. |first= Bert |year= 199...   
14094  Oh, yes; it is the glorious Fourth of July. It...   
14095           This is the last of Earth. I am content.   
14096  Principally, and first of all, I recommend my ...   
14097             See in what peace a Christian can die.   
14098                      

In [34]:
pd.set_option('display.max_colwidth', None)
print(df.loc[14088, ['quote', 'source']])

quote                                                                                                       من در حال رفتن هستم و شما مي خواهيد غذا بخورم؟ (Man dar hâl raftan hastam, va shomâ mey khâhid ghazâ békhoram? )
source    Translation: You wish Me to take some food, and I am going? Who: `Abdu'l-Bahá, son of Bahá'u'lláh and one of three central figures of the Bahá'i Faith. Note: Spoken when food was offered to him on his deathbed.
Name: 14088, dtype: object


From the chinese proverb source, last words and english proverb's sources it is confirmed that if the quote is in another language or has translation then the source contains everything.

It is upto us to whether to trim the source or keep it as it is in the datbase. It will depend on the impact it has on the size of the graph database.

Let's analyse the heading context, how many unique values it has.

In [37]:
unique_headings = df['heading_context'].nunique(dropna=True)

# List of unique authors (optional)
heading_context_list = df['heading_context'].dropna().unique()

print(f"Number of unique headings: {unique_headings}")
print(heading_context_list[:20])  # show first 20 authors

Number of unique headings: 1724
['1890s' '1900s' '1910s' 'Principles of Research (1918)' '1920s'
 'Sidelights on Relativity (1922)' 'Viereck interview (1929)' '1930s'
 'Wisehart interview (1930)' 'Religion and Science (1930)'
 'What I Believe (1930)' 'Mein Weltbild (My World-view) (1931)'
 'My Credo (1932)' '1933' '1934' 'Obituary for Emmy Noether (1935)'
 'Why Do They Hate the Jews (1938)' '1940s' 'Science and Religion (1941)'
 'Only Then Shall We Find Courage (1946)']


This seems pretty clean.

Now let's see the length of the quotes and the sources

In [42]:
df['quote_length'] = df['quote'].apply(lambda x: len(str(x)))
df['source_length'] = df['source'].apply(lambda x: len(str(x)))

# Preview
df[['quote_length', 'source_length']].describe()


quote_length  source_length
count  30000.000000   30000.000000
mean     328.241067      90.450633
std      392.587922     167.595513
min        1.000000       1.000000
25%       83.000000       5.000000
50%      187.000000      40.000000
75%      433.000000     112.250000
max    14814.000000    4356.000000

* The longest quotes is 14814 char long and the shortest quote is 1 char long.
* The longest source is 4356 char long and the shortest source is 1 char long.
Let's see them.

In [82]:
# Longest quotes
df.nlargest(5, 'quote_length')[['quote','author','source' ,'heading_context','quote_length']]

quote  \
9023   Judge: Do you want Mr. Bryan sworn? :Darrow: No. :Bryan: I can make affirmation; I can say "So help me God, I will tell the truth. ": Darrow: No, I take it you will tell the truth, Mr. Bryan. You have given considerable study to the Bible, haven't you, Mr. Bryan? :Bryan: Yes, sir, I have tried to. :Darrow: Then you have made a general study of it? :Bryan: Yes, I have; I have studied the Bible for about 50 years, or sometime more than that, but, of course, I have studied it more as I have become older than when I was but a boy. :Darrow: You claim that everything in the Bible should be literally interpreted? :Bryan: I believe everything in the Bible should be accepted as it is given there: some of the Bible is given illustratively. For instance: "Ye are the salt of the earth. " I would not insist that man was actually salt, or that he had flesh of salt, but it is used in the sense of salt as saving God's people. :Darrow: But when you read that Jonah swallowed the whale--or that the whale swallowed Jonah--excuse me please--how do you literally interpret that? :Bryan: When I read that a "big fish" swallowed Jonah--it does not say whale. That is my recollection of it. A big fish, and I believe it, and I believe in a God who can make a whale and can make a man and make both what He pleases. :Darrow: Now, you say, the big fish swallowed Jonah, and he there remained how long--three days--and then he spewed him upon the land. You believe that the big fish was made to swallow Jonah? :Bryan: I am not prepared to say that; the Bible merely says it was done. :Darrow: You don't know whether it was the ordinary run of fish, or made for that purpose? :Bryan: You may guess; you evolutionists guess. . :Darrow: You are not prepared to say whether that fish was made especially to swallow a man or not? :Bryan: The Bible doesn't say, so I am not prepared to say. :Darrow: But do you believe He made them--that He made such a fish and that it was big enough to swallow Jonah? :Bryan: Yes, sir. Let me add: One miracle is just as easy to believe as another. :Darrow: Just as hard? :Bryan: It is hard to believe for you, but easy for me. A miracle is a thing performed beyond what man can perform. When you get within the realm of miracles; and it is just as easy to believe the miracle of Jonah as any other miracle in the Bible. :Darrow: Perfectly easy to believe that Jonah swallowed the whale? :Bryan: If the Bible said so; the Bible doesn't make as extreme statements as evolutionists do. :Darrow: The Bible says Joshua commanded the sun to stand still for the purpose of lengthening the day, doesn't it, and you believe it. :Bryan: I do. :Darrow: Do you believe at that time the entire sun went around the earth? :Bryan: No, I believe that the earth goes around the sun. :Darrow: Do you believe that the men who wrote it thought that the day could be lengthened or that the sun could be stopped? :Bryan: I don't know what they thought. :Darrow: You don't know? :Bryan: I think they wrote the fact without expressing their own thoughts. :Darrow: Have you an opinion as to whether or not the men who wrote that thought--: Thomas Stewart: (a prosecution lawyer)--I want to object, your honor. It has gone beyond the pale of any issue that could possibly be injected into this lawsuit, except by imagination. I do not think the defendant has a right to conduct the examination any further and I ask your honor to exclude it. :Bryan: It seems to me it would be too exacting to confine the defense to the facts. If they are not allowed to get away from the facts, what have they to deal with? :Judge: Mr. Bryan is willing to be examined. Go ahead. :Darrow: Can you answer my question directly? If the day was lengthened by stopping either the earth or the sun, it must have been the earth? :Bryan: Well, I should say so. :Darrow: Now, Mr. Bryan, have you ever pondered what would have happened to the earth if it had stood still? :Bryan: No. :Darrow: You have not? :Bryan: No; 

Oh, the first one is a court trial so that's why it is very long.

In [47]:
# Longest sources
df.nlargest(5, 'source_length')[['quote' , 'author' , 'source', 'source_length']]

quote  \
419                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              We cannot solve the problems using the same kind of thinking we used when we created them   
417                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Two things are infinite: the universe and the human stupidity.   
8363   中国人民从中国解放区和国民党统治区，获得了明显的比较。难道还不明显吗？两条路线，人民战争的路线和反对人民战争的消极抗日的路线，其结果：一条是胜利的，即使处在中国解放区这种环境恶劣和毫无外援的地位；另一条是失败的，即使处在国民党统治区这种极端有利和取得外国接济的地位。国民党政府把自己的失败归咎于缺乏武器。但是试问：缺乏武器的是国民党的军队呢，还是解放区的军队？中国解放区的军队是中国军队中武器最缺乏的军队，他们只能从敌人手里夺取武器和在最恶劣条件下自己制造武器。国民党中央系军队的武器，不是比起地方系军队来要好得多吗？但是比起战斗力来，中央系却多数劣于地方系。国民党拥有广大的人力资源，但是在它的错误的兵役政策下，人力补充却极端困难。中国解放区处在被敌人分割和战斗频繁的情况之下，因为普遍实施了适合人民需要的民兵和自卫军制度，又防止了对于人力资源的滥用和浪费，人力动员却可以源源不竭。国民党拥有粮食丰富的广大地区，人民每年供给它七千万至一万万市担的粮食，但是大部分被经手人员中饱了，致使国民党的军队经常缺乏粮食，士兵饿得面黄肌瘦。中国解放区的主要部分隔在敌后，遭受敌人烧杀抢"三光"政策的摧残，其中有些是像陕北这样贫瘠的区域，但是却能用自己动手、发展农业生产的方法，很好地解决了粮食问题。国民党区域经济危机极端严重，工业大部分破产了，连布匹这样的日用品也要从美国运来。中国解放区却能用发展工业的方法，自己解决布匹和其他日用品的需要。在国民党区域，工人、农民、店员、公务人员、知识分子以及文化工作者，生活痛苦，达于极点。中国解放区的全体人民都有饭吃，有衣穿，有事做。利用抗战发国难财，官吏即商人，贪污成风，廉耻扫地，这是国民党区域的特色之一。艰苦奋斗，以身作则，工作之外，还要生产，奖励廉洁，禁绝贪污，这是中国解放区的特色之一。国民党区域剥夺人民的一切自由。中国解放区则给予人民以充分的自由。国民党统治者面前摆着这些反常的状况，怪谁呢？怪别人，还是怪他们自己呢？怪外国缺少援助，还是怪国民党政府的独裁统治和腐败无能呢？这难道还不明白吗？   
13790                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Anyone who is not shocked by quantum theory has not understood it.   
9755                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

Extraccting the usefull information from these long sources and the quotes to trim it is very complex. I think we should drop them.

One more operation we could perform in the preprocessing part is that for the sources which have NaN value, we could check if the quotes have :* this pattern in them. Because it represents the continuation of it. SOmetimes it contains the actual source for examples in the first longest quote. Although that quote is not useful in our case we atlest should try to split the quote in that and if it has someting we will put it into the source.

In [49]:
# Shortest quotes
df.nsmallest(5, 'quote_length')[['quote' , 'author' , 'source', 'quote_length']]

quote                author  \
579      …  Wikiquote: Templates   
4768     .             Anonymous   
5387     '             Aristotle   
5436     '             Aristotle   
5866     '                Cicero   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                source  \
579                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NaN   
4768                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Attributed to Joseph P. Kennedy Sr. in J. H. Cutler, Honey Fitz (1962), p. 291; also attributed to Knute Rockne, and others   
5387                                                                                                                                                                                                                                                                                                                                                                                                                             Every realm of nature is marvellous: and as Heraclitus, when the strangers who came to visit him found him warming himself at the furnace in the kitchen and hesitated to go in, is reported to have bidden them not to be afraid to enter, as even in that kitchen divinities were present, so we should venture on the study of every kind of animal without distaste; for each and all will reveal to us something natural and something beautiful. Book I, Part 5   
5436                                                                                                                                                                                                                                                                                                

In [53]:
# Shortest quotes
df.nsmallest(5, 'source_length')[['quote' , 'author' , 'source', 'source_length', 'heading_context']]

quote  \
2739                                                                                                                                                                                                                                                                                                                                                                                                                                                                        This is a simple story of a battle; such a tale as may be told by a soldier who is no writer to a reader who is no soldier.   
2740                                                                                                                                                                                                                                                                                                                                                                                                                        An army's bravest men are its cowards. The death which they would not meet at the hands of the enemy they will meet at the hands of their officers, with never a flinching.   
2741  Hidden in hollows and behind clumps of rank brambles were large tents, dimly lighted with candles, but looking comfortable. The kind of comfort they supplied was indicated by pairs of men entering and reappearing, bearing litters; by low moans from within and by long rows of dead with covered faces outside. These tents were constantly receiving the wounded, yet were never full; they were continually ejecting the dead, yet were never empty. It was as if the helpless had been carried in and murdered, that they might not hamper those whose business it was to fall to-morrow.   
6011                                                                                                                                                                                                                                                                                                                    Let the superior man never fail reverentially to order his own conduct, and let him be respectful to others and observant of propriety: —then all within the four seas, all men are brothers. What has the superior man to do with being distressed because he has no brothers?   
8280                                                                                                                                                                                                                                                                                    When you talk with famous scholars, the best thing is to pretend that occasionally you do not quite understand them. If you understand too little, you will be despised; if you understand too much, you will be disliked; if you just fail occasionally to understand them you will suit each other very well.   

              author source  source_length              heading_context  
2739  Ambrose Bierce      I              1  What I Saw At Shiloh (1881)  
2740  Ambrose Bierce      V              1  What I Saw At Shiloh (1881)  
2741  Ambrose Bierce      V              1  What I Saw At Shiloh (1881)  
6011       Confucius      V              1                     Analects  
8280          Lu Xun      2              1      "The Epigrams of Lusin"

* The problem with the 1 length quote and source is that in the quote part the quote is in another language so it has only scrapped the full stop. And all the following lists have been scrapped in the source it is solvable.
* Same with the source length 1. The source len 1 is the chapter and the heading contexxt is the book. So with both it becomes informative.

Lets see how many wuotes have smaller len that 5 and how many sources have smaller length than 5

In [54]:
short_quotes_count = (df['quote'].apply(lambda x: len(str(x))) < 5).sum()

# Count sources shorter than 5 characters
short_sources_count = (df['source'].apply(lambda x: len(str(x))) < 5).sum()

print(f"Quotes shorter than 5 chars: {short_quotes_count}")
print(f"Sources shorter than 5 chars: {short_sources_count}")

Quotes shorter than 5 chars: 44
Sources shorter than 5 chars: 7336


In [55]:
short_quotes_df = df[df['quote'].apply(lambda x: len(str(x)) < 5)]
print(short_quotes_df[['quote' , 'author' , 'source', 'heading_context']])

      quote                author  \
579       …  Wikiquote: Templates   
583     . .  Wikiquote: Templates   
4768      .             Anonymous   
5387      '             Aristotle   
5436      '             Aristotle   
5866      '                Cicero   
6019      '             Confucius   
7153    FAQ  Wikiquote: Utilities   
7155   Logo  Wikiquote: Utilities   
13554  ". "         Misquotations   
13703   NaN      Chinese proverbs   
13704   NaN      Chinese proverbs   
13707     ,      Chinese proverbs   
13708   NaN      Chinese proverbs   
13709   NaN      Chinese proverbs   
13710     ，      Chinese proverbs   
13712   NaN      Chinese proverbs   
13713   NaN      Chinese proverbs   
13714   NaN      Chinese proverbs   
13715   NaN      Chinese proverbs   
13716     一      Chinese proverbs   
13717   NaN      Chinese proverbs   
13718   NaN      Chinese proverbs   
13719     ，      Chinese proverbs   
13720   NaN      Chinese proverbs   
13721   NaN      Chinese proverbs   
1

most of them are meaningfull no need to delete all. We should certailny drop which author has wikiquote3 in it and others need to be checked.

now lets see the number of quotes for whom the source len is less than 2 adn the heading context is nan

In [64]:
mask = df['source'].apply(lambda x: len(str(x)) < 10) & df['heading_context'].isna()

count = mask.sum()
print("Number of quotes:", count)

# If you also want to see them:
print(df[mask][['quote', 'source', 'heading_context']])

Number of quotes: 777
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      quote  \
421                                                                                                                                                                                                                                

In [65]:
df[mask]['source'].unique()

array([nan, 'Couplet', 'Scene i', 'Scene iv', 'Scene ii', 'Scene I',
       'Scene III', 'Scene VII', 'Lennox', 'Scene IV', 'Scene II',
       'Scene iii', 'scene i', 'Prospero', 'Scene VI', "'.", 'Ibid.',
       'Scene xiv', 'p. 11', 'p. 12', 'p. 13', 'p. 15', 'p. 17', 'P. 19',
       'p. 28', 'p. 29', 'p. 32', 'p. 50', 'p. 50-51', 'p. 52', 'p. 54',
       'p. 58', 'p. 59', 'Cited in', '17.', 'Chapter 1', 'Chapter 2',
       'Chapter 3', 'Chapter 4', 'Chapter 5', 'Chapter 7', 'Chapter 9',
       'Epilogue', '.', '(2006).', 'Minotaur', 'Cicero', '{{cite',
       'Björk', 'proverb', ', p. xcv', '<', ', p. 70', ', p. 71',
       ', p. 97', ', p. 125', ', p. 115', ', p. 105', ', p. 112',
       ', p. 447', ', p. 588', ', p. 788', ', p. 657', ', p. 698',
       ', p. 463', ', p. 171', ', p. 602', ', p. 264', ', p. 512',
       ', p. 709', ', p. 723', ', p. 752', ', p. 734', ',', 'Daniel'],
      dtype=object)

There are so many we need to preprocess these too. The solution could be to search for source in the quote.
* same techique of splitting from the last encounterd :* and saving it as source.
*  We will do that in preprocessing

In [71]:
quote_len_99 = df['quote_length'].quantile(0.99)
source_len_99 = df['source_length'].quantile(0.99)

print("99th percentile quote length:", quote_len_99)
print("99th percentile source length:", source_len_99)

99th percentile quote length: 1784.0199999999968
99th percentile source length: 751.0


We need to dela with this also.

Also the thing we have to decide is that wgether we have to make node for all four features or just quote feature and all other are properties. In which way we can increase the speed and save memory.

Let's see what percentage of the source starts with translation.

In [93]:
pattern = re.compile(r'^\s*(translation|translations|translated|transliteration|transliterated|english equivalent|meaning|literal translation|pinyin:|english:|Original Latin:|)\b', re.IGNORECASE)

# check which rows match
df['starts_with_translation'] = df['source'].fillna("").apply(lambda x: bool(pattern.match(str(x))))

# calculate percentage
percentage = df['starts_with_translation'].mean() * 100

print(f"{percentage:.2f}% of sources start with 'translation', 'transliteration', or a variation")


2.11% of sources start with 'translation', 'transliteration', or a variation


This is a good number (500). How to utilise this?

In [94]:
df[df['starts_with_translation']][['quote', 'source','author','heading_context']].head(10)

quote  \
244  Einer, der nur Zeitungen liest und, wenn's hochkommt, Bücher zeitgenössischer Autoren, kommt mir vor wie ein hochgradig Kurzsichtiger, der es verschmäht, Augengläser zu tragen. Er ist völlig abhängig von den vorurteilen und Moden seiner Zeit, denn er bekommt nichts anderes zu sehen und zu hören. Und was einer selbständig denkt ohne Anlehnung an das Denken und Erleben anderer, ist auch im besten Falle Ziemlich ärmlich und monoton.   
565                                                                                                                                                                                                                                                                                                                                                                                                                                 Non-English quote.   
586                                                                                                                                                                                                                                                                                                                                                                                                                            Foreign language quote.   
601                                                                                                                                                                                                                                                                                                                                                                                                                      A diabolo, qui est simia dei.   
604                                                                                                                                                                                                                                                                                                                                                                                                                               Acquirit qui tuetur.   
607                                                                                                                                                                                                                                                                                                                                                                                                                                 Aegrescit medendo.   
608                                                                                                                                                                                                                                                                                                                                                                                                                   Aegroto dum anima est, spes est.   
609                                                                                                                                                                                                                                                                                                                                                                                                        Aeque pars ligni curvi ac recti valet igni.   
611                                                                                                                                                                                                                                                                                                                                                                                                                    Aliis si licet, tibi non licet.   
612          

What we can do is to create another property "translation" of quote nodes. And utilise this in that way. Then we will see what amount of quotes have null value of len less than 5.

Next step in the EDA is to check if the quotes or the source contains links or not.

In [78]:
url_pattern = re.compile(r'https?://\S+')

# Boolean columns for detection
df['quote_has_link'] = df['quote'].fillna("").apply(lambda x: bool(url_pattern.search(x)))
df['source_has_link'] = df['source'].fillna("").apply(lambda x: bool(url_pattern.search(x)))

# Summary counts
print("Quotes with links:", df['quote_has_link'].sum())
print("Sources with links:", df['source_has_link'].sum())

# Percentage
print("Quotes with links (%):", df['quote_has_link'].mean() * 100)
print("Sources with links (%):", df['source_has_link'].mean() * 100)

Quotes with links: 0
Sources with links: 0
Quotes with links (%): 0.0
Sources with links (%): 0.0


They don't have typical links because `I took care of that while extracting the information. But there is a pattern I noticed which is has not been taken care of
* {{ cite book

In [91]:
pattern = r"\{\{\s*cite\s+book"
count = df['source'].fillna("").str.contains(pattern, case=False, regex=True).sum()

print(f"Number of sources containing '{{{{cite book}}}}': {count}")


Number of sources containing '{{cite book}}': 47


In [92]:
matches = df[df['source'].fillna("").str.contains(pattern, case=False, regex=True)]
print(matches[['quote', 'source']])

There are 47 quotes which has {{ cite book in it but the one which ends with it are meaning less. So we will delete only the quotes which ends with {{cite boo and leave others.

Let's see if we have any duplicate quotes

In [100]:
# Find duplicates based on BOTH quote and source
duplicates = df[df.duplicated(subset=['quote', 'source', 'author'], keep=False)]
# pd.set_option('display.max_colwidth', None)
# See how many there are
print(f"Total duplicate rows (quote+source): {duplicates.shape[0]}")

# View some examples
duplicates.sort_values(by='quote').head(20)

Total duplicate rows (quote+source): 88


quote  \
23577                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Well done" is better than "well said".   
24081                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Well done" is better than "well said".   
566                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         (. . quote. . )   
567                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         (. . quote. . )   
568                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

There are multiple duplicates in the dataset. We have to remove them also

Now I think the EDA is complete let's preprocess the dataframe 

### Preprocessing

Let's write down the steps in the preprocessing.
* I have to deal with the rows corresponding to the null quote values. Either extract quopte from the sourcce or remove them.(most of them are chinese proverbs)
* delete wikiquote pages
* deal with unit len quote and source
* deal with very large quote and source
* One more operation we could perform in the preprocessing part is that for the sources which have NaN value, we could check if the quotes have :* this pattern in them. Because it represents the continuation of it. Sometimes it contains the actual source for examples in the first longest quote. Although that quote is not useful in our case we atlest should try to split the quote in that and if it has someting we will put it into the source.
* check if the source has only [nan, 'Couplet', 'Scene i', 'Scene iv', 'Scene ii', 'Scene I',
       'Scene III', 'Scene VII', 'Lennox', 'Scene IV', 'Scene II',
       'Scene iii', 'scene i', 'Prospero', 'Scene VI', "'.", 'Ibid.',
       'Scene xiv', 'p. 11', 'p. 12', 'p. 13', 'p. 15', 'p. 17', 'P. 19',
       'p. 28', 'p. 29', 'p. 32', 'p. 50', 'p. 50-51', 'p. 52', 'p. 54',
       'p. 58', 'p. 59', 'Cited in', '17.', 'Chapter 1', 'Chapter 2',
       'Chapter 3', 'Chapter 4', 'Chapter 5', 'Chapter 7', 'Chapter 9',
       'Epilogue', '.', '(2006).', 'Minotaur', 'Cicero', '{{cite',
       'Björk', 'proverb', ', p. xcv', '<', ', p. 70', ', p. 71',
       ', p. 97', ', p. 125', ', p. 115', ', p. 105', ', p. 112',
       ', p. 447', ', p. 588', ', p. 788', ', p. 657', ', p. 698',
       ', p. 463', ', p. 171', ', p. 602', ', p. 264', ', p. 512',
       ', p. 709', ', p. 723', ', p. 752', ', p. 734', ',', 'Daniel'],
      dtype=object) and no heading context or author. If these two are not present the source itself is not meaning full. so we have to deal with it. Or see if the quotes contains source :* after this pattern. if yes then I will extract that form the quote and put in the source/
* Also the thing we have to decide is that wgether we have to make node for all four features or just quote feature and all other are properties. In which way we can increase the speed and save memory.
* 2.11% of sources start with 'translation', 'transliteration', or a variation. What we can do is to create another property "translation" of quote nodes. And utilise this in that way. Then we will see what amount of quotes have null value of len less than 5.
* There are 47 quotes which has {{ cite book in it but the one which ends with it are meaning less. So we will delete only the quotes which ends with {{cite boo and leave others.
* There are 88 duplicate rows need to delete them.

Remove htmls. wikiquotes authers, some patterns from the quote and source text.

So we have two options for chinese proverbs

to drop the columns for which the quote is NaN value.
to switch the source and the quote value where the quote is NaN. Because the source contains the translation and in a way it is also a quote. we will decide in the preprocessing part

We should do something for  Albert einstien and misattributed to ALbert Einstien and disputed with albert Einstin are three different authors in the author list. Which is a entity fragmentation. Wer should think like we should put the author as a node in the databse or the property of the quote in the databse. If the author is a node then these three variations should be replaced with one author node and the misattributed and disputed should be property of code for better memory utilisation

One more operation we could perform in the preprocessing part is that for the sources which have NaN value, we could check if the quotes have :* this pattern in them. Because it represents the continuation of it. SOmetimes it contains the actual source for examples in the first longest quote. Although that quote is not useful in our case we atlest should try to split the quote in that and if it has someting we will put it into the source.

Drop wikiquote templates


We will check the single length quote rows and max len in the preprocessing

First of all let's drop the wikiquote template and duplicates

In [26]:
df = df[df["author"].ne("Wikiquote: Templates")].reset_index(drop=True)
df = df[df["author"].ne("Wikiquote: Requests")].reset_index(drop=True)
df = df[df["author"].ne("Wikiquote: Utilities")].reset_index(drop=True)
df = df.drop_duplicates(subset=["quote", "source", "heading_context"]).reset_index(drop=True)


ALso let's remove every entry related to wikkiquote as author

In [38]:
# Find rows where author starts with "Wikiquote:"
wikiquote_authors = df_new[df_new["author"].astype(str).str.startswith("Wikiquote:")]
wikiquote_authors


quote  \
3926                                                                       Famous speeches of historical value can be added to the speeches portal at Wikisource.   
3927                                                      Whole public domain books can be added to Wikisource or Wikibooks, see Wikisource Project: Annotations.   
3928                                                                                  Generic deposits of published information may be appropriate at Wikisource.   
3929   Book PDFs/DJVUs, pictures, sound files, and other forms of media that are in the public domain or under a libre license are accepted at Wikimedia Commons.   
3930                                                                                                                             Wikipedia: What Wikipedia is not   
...                                                                                                                                                           ...   
25713                                                                         Themebot - whether we should have an automatic theme generator. (abandoned concept)   
25714                                                                                      Logo - what the Wikiquote logo should be. (has been chosen) Wikiquote|   
26628                                                                                                                                             "sourced quote"   
26629                                                                                                       "moved to Misattributed after finding original quote"   
26630                                                                                                                                 "removed likely prank edit"   

      source                                     author heading_context  
3926     NaN           Wikiquote: What Wikiquote is not             NaN  
3927     NaN           Wikiquote: What Wikiquote is not             NaN  
3928     NaN           Wikiquote: What Wikiquote is not             NaN  
3929     NaN           Wikiquote: What Wikiquote is not             NaN  
3930     NaN           Wikiquote: What Wikiquote is not             NaN  
...      ...                                        ...             ...  
25713    NaN                          Wikiquote: Issues             NaN  
25714    NaN                          Wikiquote: Issues             NaN  
26628    NaN  Wikiquote: Sourced and Unsourced sections             NaN  
26629    NaN  Wikiquote: Sourced and Unsourced sections             NaN  
26630    NaN  Wikiquote: Sourced and Unsourced sections             NaN  

[185 rows x 4 columns]

In [92]:
df = df[~df["author"].astype(str).str.startswith("Wikiquote:")].reset_index(drop=True)
df = df[~df["author"].astype(str).str.startswith("List of categories")].reset_index(drop=True)
# List of categories

In [93]:
df["quote"] = df["quote"].replace("NaN", np.nan)

# Regex: only spaces or punctuation (no letters/numbers)
only_special_pattern = r'^[^\w\u4e00-\u9fff]+$'  # excludes alphanumerics + Chinese chars

mask = (
    df["quote"].isna() | 
    df["quote"].astype(str).str.fullmatch(only_special_pattern)
)

# Filter
special_or_nan_quotes = df[mask]

print(f"Found {len(special_or_nan_quotes)} rows")
display(special_or_nan_quotes)

Found 32 rows


quote  \
4656           .   
5275           '   
5324           '   
5754           '   
5907           '   
13404       ". "   
13549  ， ， ， ； 。   
13553        NaN   
13554        NaN   
13557          ,   
13558        NaN   
13559        NaN   
13560          ，   
13562        NaN   
13563        NaN   
13564        NaN   
13565        NaN   
13567        NaN   
13568        NaN   
13569          ，   
13570        NaN   
13571        NaN   
13572          ，   
13574        NaN   
13576          ，   
13577          ，   
13578        NaN   
13579          ，   
13581        NaN   
13582        NaN   
14154          '   
24873          ?   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  source  \
4656                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Attributed to Joseph P. Kennedy Sr. in J. H. Cutler, Honey Fitz (1962), p. 291; also attributed to Knute Rockne, and others   
5275                          

In [94]:
# Missing values
print(df.isna().sum())

quote                16
source             6846
author                0
heading_context    9150
dtype: int64


We can see that the source has multiple translation, pinyin, and other headings and values. We can convert this to dictionary and use one of the value as the quote if the value of the quote is meaning less.

In [95]:

def parse_kv(text, keys=None):
    if not isinstance(text, str) or not text.strip():
        return {}
    if keys is None:
        keys = [
            "Transliteration (pinyin)", "Transliteration", "Pinyin",
            "Traditional", "Simplified", "Meaning", "Literal",
            "Translation", "Variant", "Notes", "Source","who"
        ]
    key_alt = "|".join(map(re.escape, keys))
    pat = re.compile(rf"(?i)\b({key_alt})\b\s*:", re.DOTALL)
    matches = list(pat.finditer(text))
    if not matches:
        return {}
    out = {}
    for i, m in enumerate(matches):
        key_raw = m.group(1)
        start = m.end()
        end = matches[i+1].start() if i+1 < len(matches) else len(text)
        val = text[start:end].strip()
        val = re.sub(r"\s+", " ", val).strip(" \t\n\r\"'，。；;:,-")
        if key_raw in out and val:
            out[key_raw] = f"{out[key_raw]} | {val}"
        elif val:
            out[key_raw] = val
    return out



In [96]:
df_new = df.copy()

for idx in df_new[mask].index:
    kv = parse_kv(df_new.at[idx, "source"])
    if kv:
        # Take first key's value
        first_val = next(iter(kv.values()))
        df_new.at[idx, "quote"] = first_val

        # Remove that key/value from the source text
        first_key = next(iter(kv.keys()))
        pattern = re.compile(rf"{re.escape(first_key)}\s*:\s*{re.escape(first_val)}", re.IGNORECASE)
        df_new.at[idx, "source"] = pattern.sub("", df_new.at[idx, "source"], count=1).strip()

df_new[mask]

quote  \
4656                                                                                                             .   
5275                                                                                                             '   
5324                                                                                                             '   
5754                                                                                                             '   
5907                                                                                                             '   
13404                                                                                                         ". "   
13549                                                                         不聞不若聞之，聞之不若見之，見之不若知之，知之不若行之；學至於行之而止矣   
13553                                                                                                      長江後浪推前浪   
13554                                                                                                   讀萬卷書不如行萬裡路   
13557                                                                                                   福無重至, 禍不單行   
13558                                                                                                         父債子還   
13559                                                                                                      害人之心不可有   
13560                                                                                                      今日事，今日畢   
13562                                                                                                    空穴來風，未必無因   
13563                                                                                                         良藥苦口   
13564  Yǒu qí fù bì yǒu qí zǐ. Having such a father must be such a son. English equivalent: Like father, like son.   
13565                                                                                                       人算不如天算   
13567                                                                                                      三個和尚沒水喝   
13568                                                                                                       死馬當活馬醫   
13569                                                                                                  師傅領進門，修行在個人   
13570                                                                                                   授人以魚不如授之以漁   
13571                                                                                                        樹倒猢猻散   
13572                                                                                                    水能載舟，亦能覆舟   
13574                                                                                                        天高皇帝遠   
13576                                                                                                  一朝被蛇咬，十年怕井繩   
13577                                                                                                    一分耕耘，一分收穫   
13578                                                                                                      有錢能使鬼推磨   
13579                                                                                              一失足成千古恨，再回頭已百年身   
13581                                                                                                        自助者天助   
13582                                                                                                     早起的鳥兒有蟲吃   
14154                                                                                           Where is my clock?   
24873                                                                                                            ?   

                                                                                                                                                                                                                      

In [97]:
print(df_new.isna().sum())

quote                 0
source             6846
author                0
heading_context    9150
dtype: int64


deleting the only punctuation quotes

In [98]:
only_punct_pattern = r'^[^\w\u4e00-\u9fff]+$'

# Mask for "only punctuation"
mask_only_punct = df_new["quote"].astype(str).str.fullmatch(only_punct_pattern)

# Preview them before removal
punct_only_rows = df_new[mask_only_punct]
punct_only_rows

# Remove them
df_new = df_new[~mask_only_punct].reset_index(drop=True)

In [99]:
short_quotes_count_new = (df_new['quote'].apply(lambda x: len(str(x))) < 5).sum()

print(f"Quotes shorter than 10 chars: {short_quotes_count_new}")

short_quotes_df_new = df_new[df_new['quote'].apply(lambda x: len(str(x)) < 5)]
short_quotes_df_new[['quote' , 'author' , 'source', 'heading_context']]

Quotes shorter than 10 chars: 10


quote            author  \
13552  父債子還  Chinese proverbs   
13557  良藥苦口  Chinese proverbs   
13560     一  Chinese proverbs   
13588  光阴似箭  Chinese proverbs   
14001   No.        Last words   
14563  V-1.        Last words   
14727  Yeah        Last words   
14740   No.        Last words   
14877  Yes.        Last words   
14938   No.        Last words   

                                                                                                                                                                                                                                                                                                                                                                                                                                                              source  \
13552                                                                                       Transliteration (pinyin): Fù zhài zǐ huán.  Simplified: 父债子还 Father's debt, son to give back. Meaning: The new generation can fix the mistakes made by previous ones. "New generation can put right the mistakes of the old. " "To do the opposite of something is also a form of imitation. " Georg Lichtenberg, The Waste Books, R. J. Hollingdale trans. (2000), D96.   
13557                                                                                                                                                                                          Transliteration (pinyin): Liángyào kǔkǒu  Simplified: 良药苦口 Good medicine tastes bitter. Meaning: What may be good for us later may be hard for us now. English equivalent: Bitter pills may have blessed effects. "Present afflictions may tend to our future good. "   
13560                                                                                                                                                                                                                             Transliteration (pinyin): Ròu bāozi dǎ gǒu 一 qù bù huítóu. Traditional: 肉包子打狗一去不回頭 Simplified: 肉包子打狗一去不回头 To hit a dog with a meat-bun, so it leaves never turning around. Meaning: Punishment gives less incentive than a reward.   
13588                                                                                                                                                                                                                                                                                                                                                                                                                  English equivalent: Time flies like an arrow.   
14001                                                                                                                                                               Who: Alexander Graham Bell, a Scottish-born scientist, inventor, engineer and innovator who is credited with patenting the first practical telephone. Note: While Alexander Graham Bell was dying, his deaf wife whispered to him, "Don't leave me. " Bell responded by signing the word, "No. "   
14563  Who: Klaas Meurs Note: Klaas Meurs was the First Officer of KLM Flight 4805, which crashed on take-off on March 27th 1977, killing 583 people when it collided with a Pan Am Boeing 747, killing all 248 on Flight 4805 (including Meurs) and 335 on the Pan Am Aircraft. His last words of "V-1" where the Aviation terminology used when an Aircraft is going too fast to cancel the take-off and must take-off. Eight seconds later, both planes collided.   
14727                                                                                                                                                                                                                                                                                                                                                                                                                                                            N

But first let's delete the rows having the author unknown, source NaN and heading_context = NaN

In [100]:
mask_del = (
    df_new["author"].astype(str).str.strip().str.lower().eq("unknown") &
    (
        df_new["source"].isna() |
        df_new["source"].astype(str).str.fullmatch(only_punct_pattern)
    ) &
    df_new["heading_context"].isna()
)

# Preview before deletion
display(df_new[mask_del])

# Delete them
df_new = df_new[~mask_del].reset_index(drop=True)

quote  \
542                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        His work revolved around three rules which apply to all science, our problems, and times:   
543                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

In [101]:
# Mask: source length < 5 AND heading_context is NaN
mask_src_short_no_context = (
    df_new["source"].astype(str).str.len() < 5
) & (
    df_new["heading_context"].isna()
)

# Preview the rows
short_source_no_context = df_new[mask_src_short_no_context]
display(short_source_no_context)


quote  \
421                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Stay away from negative people. They have a problem for every solution.   
1539                                                                                                                                                                Republicans approve of the American farmer, but they are willing to help him go broke. They stand four-square for the American home--but not for housing. They are strong for labor--but they are stronger for restricting labor's rights. They favor minimum wage--the smaller the minimum wage the better. They endorse educational opportunity for all--but they won't spend money for teachers or for schools. They think modern medical care and hospitals are fine--for people who can afford them. . .They think the American standard of living is a fine thing--so long as it doesn't spread to all the people. And they admire the Government of the United States so much that they would like to buy it. − Harry S. Truman, October 13, 1948, St. Paul, Minnesota, Radio Broadcast. https: //www. trumanlibrary. gov/library/public-papers/236/address-st-paul-municipal-auditoriumhttp: //www. presidency. ucsb. edu/ws/index. php? pid=13046https: //www. goodreads. com/quotes/97983-republicans-approve-of-the-american-farmer-but-they-are-willinghttps: //www. snopes. com/politics/quotes/trumangop. asphttps: //spydersden. wordpress. com/2014/11/22/ten-quotes-about-republicans-from-harry-truman/https: //www. nytimes. com/2017/11/24/opinion/republican-taxes-healthcare. html#permid=24954077   
1540                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

From the quote extracting the source if it is missing.

In [102]:
# import re
# import numpy as np
# import pandas as pd

# # consider "only punctuation/whitespace" as empty
ONLY_PUNCT_RE = r'^[^\w\u4e00-\u9fff]+$'

# split on variations like ":*", ": *", "：*", multiple asterisks, extra spaces
CONT_SPLIT_RE = re.compile(r'\s*[:：]\s*\*+\s*')

def clean_text(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = re.sub(r"\s+", " ", s).strip()
    # trim common trailing punctuation clutter
    return s.strip(" \t\n\r\"'，。；;:,-")

def pick_candidate(chunks):
    """
    Choose the best 'source-like' chunk:
    - prefer the longest non-empty, non-punctuation chunk
    - length >= 5 characters (tweakable)
    """
    cleaned = [clean_text(c) for c in chunks if isinstance(c, str)]
    # drop empty / punctuation-only
    cleaned = [c for c in cleaned if c and not re.fullmatch(ONLY_PUNCT_RE, c)]
    if not cleaned:
        return ""
    # choose the longest
    return max(cleaned, key=len)

# 1) Build a mask: source is NaN and quote contains a ':*' continuation
mask_continuation = df_new["source"].isna() & df_new["quote"].astype(str).str.contains(CONT_SPLIT_RE)

# 2) Preview what would change (no mutations yet)
preview = []
for idx in df_new[mask_continuation].index:
    q = df_new.at[idx, "quote"]
    parts = CONT_SPLIT_RE.split(q)
    if len(parts) < 2:
        continue
    # everything after the first chunk are candidates for source
    candidate = pick_candidate(parts[1:])
    if candidate:
        preview.append({
            "index": idx,
            "old_quote": q,
            "new_quote": clean_text(parts[0]),
            "new_source_candidate": candidate
        })

preview_df = pd.DataFrame(preview)
display(preview_df.head(20))  # <- review here
print(f"Rows with candidate source found: {len(preview_df)}")


index  \
0    1412   
1    1413   
2    3812   
3    4567   
4    7029   
5    7399   
6    7577   
7    7625   
8    7626   
9    7627   
10   7628   
11   7629   
12   7630   
13   7722   
14   7773   
15   8862   
16   9276   
17   9340   
18  10293   
19  10414   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

Rows with candidate source found: 46


In [103]:
for row in preview:
    idx = row["index"]
    df_new.at[idx, "quote"]  = row["new_quote"]
    df_new.at[idx, "source"] = row["new_source_candidate"]

# (optional) tidy any quotes that became empty/punct-only after trimming
mask_bad_quote = df_new["quote"].astype(str).str.fullmatch(ONLY_PUNCT_RE) | df_new["quote"].isna()
# decide whether to drop or leave them; example drops them:
df_new = df_new[~mask_bad_quote].reset_index(drop=True)

In [104]:
mask_bad_quote

0        False
1        False
2        False
3        False
4        False
         ...  
29670    False
29671    False
29672    False
29673    False
29674    False
Name: quote, Length: 29675, dtype: bool

Now let's see the rows which have sources length less than 5 but other than NaN

In [105]:
# rows with non-NaN source and length < 5 (after stripping whitespace)
mask_src_short = df_new["source"].notna() & (df_new["source"].astype(str).str.strip().str.len() < 5)

short_sources = df_new[mask_src_short]
print(f"Rows found: {len(short_sources)}")
display(short_sources)

Rows found: 248


quote  \
355    School failed me, and I failed the school. It bored me. The teachers behaved like Feldwebel (sergeants). I wanted to learn what I wanted to know, but they wanted me to learn for the exam. What I hated most was the competitive system there, and especially sports. Because of this, I wasn't worth anything, and several times they suggested I leave. This was a Catholic School in Munich. I felt that my thirst for knowledge was being strangled by my teachers; grades were their only measurement. How can a teacher understand youth with such a system? . . from the age of twelve I began to suspect authority and distrust teachers. I learned mostly at home, first from my uncle and then from a student who came to eat with us once a week. He would give me books on physics and astronomy. The more I read, the more puzzled I was by the order of the universe and the disorder of the human mind, by the scientists who didn't agree on the how, the when, or the why of creation. Then one day this student brought me Kant's Critique of Pure Reason. Reading Kant, I began to suspect everything I was taught. I no longer believed in the known God of the Bible, but rather in the mysterious God expressed in nature.   
1636                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      The conception of the necessary unit of all that is resolves itself into the poverty of the imagination, and a freer logic emancipates us from the straitwaistcoated benevolent institution which idealism palms off as the totality of being.   
1637                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    The true function of logic. . as applied to matters of experience. . is analytic rather than constructive; taken a priori, it shows the possibility of hitherto unsuspected alternatives more often than the impossibility of alternatives which seemed prima facie possible. Thus, while it liberates imagination as to what the world may be, it refuses to legislate as to what the world is.   
1985                                                                                                                                                                                                                                                                                                                                                        When I 

Let's check if the source have these pages, chapter, I,II and heading context have NaN. We will drop them too

In [106]:
print(df_new.isna().sum())

quote                 0
source             6770
author                0
heading_context    9115
dtype: int64


In [107]:

# ONLY_PUNCT_RE   = r'^[^\w\u4e00-\u9fff]+$'              # only punctuation/space
CONT_SPLIT_RE   = re.compile(r'\s*[:：]\s*\*+\s*')       # :*, ：*, : **, etc.

def clean_text(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = re.sub(r"\s+", " ", s).strip()
    return s.strip(" \t\n\r\"'，。；;:,-")

def pick_candidate(chunks):
    """Pick the longest non-empty, non-punct-only chunk."""
    cleaned = [clean_text(c) for c in chunks if isinstance(c, str)]
    cleaned = [c for c in cleaned if c and not re.fullmatch(ONLY_PUNCT_RE, c)]
    return max(cleaned, key=len) if cleaned else ""

# literals that are never meaningful as a full source *by themselves*
LITERAL_BAD_SOURCES = {
    ".", ",", "'.", "<",
    "Couplet", "Epilogue", "proverb",
    "Lennox", "Prospero", "Minotaur", "Cicero", "Björk", "Daniel",
}

# regexes for common “not meaningful” patterns (case-insensitive)
BAD_SOURCE_PATTERNS = [
    re.compile(r"^\s*scene\s*[ivxlcdm]+\s*$", re.I),           # Scene iv, Scene III, etc.
    re.compile(r"^\s*chapter\s*\d+\s*$", re.I),                # Chapter 1, Chapter 12
    re.compile(r"^\s*,?\s*p\.\s*(?:\d+|[ivxlcdm]+)(?:-\d+)?\s*$", re.I),  # p. 11, , p. xcv, p. 50-51
    re.compile(r"^\s*ibid\.?\s*$", re.I),                      # Ibid.
    re.compile(r"^\s*cited in\b.*$", re.I),                    # Cited in ...
    re.compile(r"^\s*\{\{cite.*$", re.I),                      # {{cite ...}}
    re.compile(ONLY_PUNCT_RE),                                 # only punctuation
    re.compile(r"^\s*[ivxlcdm]+\s*$", re.I),                   # bare Roman numeral: I, II, III...
    re.compile(r"^\s*\(2006\)\.\s*$", re.I),                   # (2006).
]

def source_is_meaningless(x) -> bool:
    """True if source is NaN OR one of the known 'meaningless' forms above."""
    if pd.isna(x):
        return True
    t = str(x).strip()
    if not t:
        return True
    if t in LITERAL_BAD_SOURCES:
        return True
    low = t.lower()
    if low in {s.lower() for s in LITERAL_BAD_SOURCES}:
        return True
    for pat in BAD_SOURCE_PATTERNS:
        if pat.fullmatch(t):
            return True
    return False

# --- build masks -----------------------------------------------------------

# "no heading context"
mask_no_context = df_new["heading_context"].isna()

# "no author" (strict NaN). If you also want to treat 'unknown' as missing, add .str.lower().eq('unknown')
mask_no_author  = df_new["author"].isna()

# source meaningless (includes NaN)
mask_bad_source = df_new["source"].apply(source_is_meaningless)

# rows to handle
mask_targets = mask_no_context & mask_no_author & mask_bad_source
targets = df_new[mask_targets]
print(f"Candidates to handle (bad source + no context/author): {len(targets)}")
# display(targets.head(20))  # uncomment to preview


Candidates to handle (bad source + no context/author): 0


In [114]:

cite_book_only = re.compile(r'^\s*\{\{\s*cite\s*book\b.*?\}\}\s*$', re.IGNORECASE | re.DOTALL)

# 2) Only an unclosed/truncated {{cite book ...}} tail
cite_book_truncated_only = re.compile(r'^\s*\{\{\s*cite\s*boo?k?\s*$', re.IGNORECASE)

mask_cite_only = df_new["source"].fillna("").str.match(cite_book_only)
mask_cite_trunc = df_new["source"].fillna("").str.match(cite_book_truncated_only)

rows_cite_only = df_new[mask_cite_only | mask_cite_trunc]

print(f"Rows where source is ONLY a cite book template (closed or truncated): {len(rows_cite_only)}")
display(rows_cite_only[["quote","author","source","heading_context"]])


Rows where source is ONLY a cite book template (closed or truncated): 0


Empty DataFrame
Columns: [quote, author, source, heading_context]
Index: []

In [113]:
# setting them to NaN
df_new.loc[mask_cite_only | mask_cite_trunc, "source"] = np.nan


In [117]:
df_new.head(5)

quote  \
0                                                                                                                                                                                                                                                                                                                                                                                                        Un homme heureux est trop content du présent pour trop se soucier de l'avenir.   
1  Autoritätsdusel ist der größte Feind der Wahrheit. :: Another translation: Authority gone to one's head is the greatest enemy of truth. (Collected Papers, Volume 1, 1987): * Letter to Jost Winteler (July 8th, 1901), quoted in The Private Lives of Albert Einstein by Roger Highfields and Paul Carter (1993), p. 79. Einstein had been annoyed that Paul Drude, editor of Annalen der Physik, had dismissed some criticisms Einstein made of Drude's electron theory of metals.   
2                                                                                                                                                                         Lieber Habicht! / Es herrscht ein weihevolles Stillschweigen zwischen uns, so daß es mir fast wie eine sündige Entweihung vorkommt, wenn ich es jetzt durch ein wenig bedeutsames Gepappel unterbreche. . / Was machen Sie denn, Sie eingefrorener Walfisch, Sie getrocknetes, eingebüchstes Stück Seele. . ?   
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 E=mc²   
4                                                                                                                                                                                                                                                                                                                                                                                                                                The mass of a body is a measure of its energy content.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     source  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

In [118]:
df_new.to_csv("Preprocessed_quotes_dataframe.csv", index=False)
print("Saved:", "Preprocessed_quotes_dataframe.csv")

Saved: Preprocessed_quotes_dataframe.csv


In [120]:
df_2 = pd.read_csv("extracted_quotes_about.csv" , index_col = False)

In [121]:
df2_auth = (
    df_2
    .dropna(subset=["author"])  # only rows that actually have an author
    .drop_duplicates(subset=["quote", "source", "heading_context"], keep="first")
    [["quote", "source", "heading_context", "author"]]
    .rename(columns={"author": "author_new"})
)

# 2) Join onto df_new
merged = df_new.merge(
    df2_auth,
    on=["quote", "source", "heading_context"],
    how="left",
)

# 3) Preview planned changes
to_update = merged["author_new"].notna() & (merged["author"].fillna("") != merged["author_new"].fillna(""))
print(f"Rows to update: {to_update.sum()}")
display(merged.loc[to_update, ["quote", "source", "heading_context", "author", "author_new"]].head(20))


Rows to update: 5288


quote  \
464                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      These days it is common knowledge that short waves are more powerful than long ones, as the very short ones, known as x-rays, damage living tissues. It took half-a-century to learn this fact: it was one of the great discoveries of young Albert Einstein of 1905. When he announced it leading researchers found it most incredible. .   
465                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         . . do not be impressed by the imprint of a famous publishing house or the volumes of an author's publications. Bear in mind that Einstein needed only seventeen pages for his contribution which revolutionized physics, while there are graphomanics in asylums who use up mounds of paper every day.   
466                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Paula Gunn Allen's description of the tribal culture is helpful in understanding this concept of energy dispersal: "The closest analogy in Western thought is the Einsteinian understanding of matter as a special state or condition of energy. Yet even this concept falls short of the Native American understanding, for Einsteinian energy is essentially stupid, while energy in the Indian view is intelligence manifesting yet another way. "   
467                                                                                                                                                                                                                                                                                                                               

In [122]:
merged.loc[to_update, "author"] = merged.loc[to_update, "author_new"]
df_new_updated = merged.drop(columns=["author_new"]).reset_index(drop=True)

In [123]:
merged.loc[to_update, "author"] = merged.loc[to_update, "author_new"]
df_new_updated.shape

(29675, 4)

Let's also trim the extra starting and ending spaces and punctuations from the quotes before saving.

In [125]:
EDGE_CHARS = ' \t\r\n.,;:!?\'"“”‘’«»‹›()[]{}<>|/\\·•…`~--–—-'

def trim_edges(series: pd.Series) -> pd.Series:
    s = series.astype("object")               # keeps NaNs
    mask = s.notna()
    s.loc[mask] = (
        s.loc[mask].astype(str)
        .str.replace(r"\s+", " ", regex=True) 
        .str.strip(EDGE_CHARS)                
    )
    return s

df_new_updated["quote"]  = trim_edges(df_new_updated["quote"])



In [129]:
def parse_author(author):
    if pd.isna(author):
        return "canonical", "unknown"

    a = author.strip()
    lower = a.lower()

    if lower.startswith("about "):
        return "about", a[6:].strip()
    elif lower.startswith("misattributed to "):
        return "misattributed", a[17:].strip()
    elif lower.startswith("disputed with "):
        return "disputed", a[13:].strip()
    elif lower == "unknown":
        return "canonical", "unknown"
    else:
        return "canonical", a  # plain confirmed name

df_new_updated[["status", "target_name"]] = df_new_updated["author"].apply(
    lambda x: pd.Series(parse_author(x))
)

# now save with spread columns
df_new_updated.to_csv("quotes_spread.csv", index=False)

In [134]:
df_new_updated["quote"] = df_new_updated["quote"].astype(str).str.strip()
df_new_updated["source"] = df_new_updated["source"].astype(str).fillna("").str.strip()

# Lengths
q_len = df_new_updated["quote"].str.len()
s_len = df_new_updated["source"].str.len()

# 1) Drop long quotes
removed_quotes = (q_len > 1000).sum()
df_new = df_new_updated[q_len <= 1000].copy()

# 2) Keep row, but cap source to 1000 chars (or 300 if you prefer)
df_new["source"] = df_new_updated["source"].str.slice(0, 1000)

print(f"Removed {removed_quotes} quotes >1000 chars; kept {len(df_new)} rows.")

Removed 1813 quotes >1000 chars; kept 27862 rows.


In [135]:
df_new.shape

(27862, 6)

In [137]:
df_new.to_csv("quotes_database_final.csv", index=False)

In [126]:
df_new_updated.to_csv("Preprocessed_quotes_dataframe_updated_1.csv", index=False)
print("Saved:", "Preprocessed_quotes_dataframe_updated_1.csv")

Saved: Preprocessed_quotes_dataframe_updated_1.csv


In [138]:
pip install fastapi



   ---------------------------------------- 0/2 [starlette]
   ---------------------------------------- 0/2 [starlette]
   ---------------------------------------- 0/2 [starlette]
   -------------------- ------------------- 1/2 [fastapi]
   -------------------- ------------------- 1/2 [fastapi]
   -------------------- ------------------- 1/2 [fastapi]
   -------------------- ------------------- 1/2 [fastapi]
   ---------------------------------------- 2/2 [fastapi]



In [139]:
pip install uvicorn 

In [140]:
pip install neo4j

What I did above is that, first time I extracted the information frOm the dump when the heading was quote about I set the author as unknown. I reextracted the information after changing the extractor little bit. This time I set the author as about title when the heading is quote about or quote for. And then merged replaced in the new dataframe.

* Now the preprocessing is almost done. The only thing I have to decide is the len of the quote and source.
* And the nodes and the properties of the graph datbase.